### ISSUE TITLE
line_end_date in rwTO-oT_LoT_line.py

### ISSUE THREAD

**Issue by jwu19** [Merck/Line-of-Therapy-Algorithm#1]
The line end date should be MED_START or MED_END? in line 154 in rwTO-oT_LoT_line.py: line_end_date = max(temp_line_end_df['MED_START'])

**Comment by Weilin37** [comment]
This is done because often times the dataset will not have a date column that specifies a true MED_END date. Instead, many datasets will just have one column which is the start of medication or MED_START. In those cases, the best one can do is tax the maximum of the MED_START date as the line_end date

**Comment by jwu19** [comment]
got it, thank you for clarifying that
